### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by palja33** [MATF-RG17/RG038-curling#1]

**Comment by ivan-cukic-matf** [comment]
Otvorite ovaj issue ponovo kad zavrsite #2 i #3

**Comment by palja33** [comment]
Po difoltu je bilo namesteno gadjanje sa 2 kugle sad sam povecao broj na 4, a za vise kugli od toga je potrebno navesti broj kao drugi argument komandne linije i onda ce svaki od igraca imati po toliko kugli da baci

**Comment by ivan-cukic-matf** [comment]
Dodajte uputstvo za koriscenje u README.md
