### ISSUE TITLE
Omogucite gadjanje sa vise 'kugli'

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG038-curling#3]
Umesto da je limit po 2, refaktorisite kod tako da je moguce gadjati proizvoljan broj puta (napravite niz kugli)

**Comment by palja33** [comment]
Popravljeno

**Comment by ivan-cukic-matf** [comment]
I dalje ne dozvoljava više od dve kugle po igracu - posle ispaljene 4 kugle, 'r' vise ne radi (bar meni)

**Comment by palja33** [comment]
Po difoltu je bilo namesteno gadjanje sa 2 kugle sad sam povecao broj na 4, a za vise kugli od toga je potrebno navesti broj kao drugi argument komandne linije i onda ce svaki od igraca imati po toliko kugli da baci
